# Server
server.port=8088
#server.servlet.context-path=/api
application.version=1.0.0
app.retry.max.attempts=3
# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

#PostgreSQL DB Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_db
spring.datasource.username=bduser
spring.datasource.password=bdpassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:/db/migration
#this is setting temporarily
spring.flyway.validate-on-migrate=false

#Mail Server
spring.mail.host=smtp.gmail.com
spring.mail.port=587
app.password=qrnx npiw faqf mztp
spring.mail.username=aunkurdas1111@gmail.com
spring.mail.password=${app.password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

#Blood Donation Properties
min.days.between.donation=90

#KafkaConfiguration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages= com.bd.blooddonorfinder.payload.request.DonorSearchRequest;
spring.kafka.consumer.group-id=notification-consumer-group

kafka.event.source=blood-donor-service

#Kafka Producer Configuration
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
kafka.producer.max-publish-retries=3
spring.kafka.producer.batch-size=16384
spring.kafka.producer.buffer-memory=33554432
spring.kafka.producer.compression-type=snappy
spring.kafka.producer.properties.max.in.flight.requests.per.connection=3

#Kafka Consumer Configuration
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.max-poll-records=100
spring.kafka.consumer.concurrency=3
spring.kafka.consumer.max-retries=3
spring.kafka.consumer.retry-interval-ms=1000
spring.kafka.consumer.poll.timeout=3000

#Application-specific Kafka settings
kafka.topics.eligible-donors=blood-donor-notifications
kafka.consumer.group-id=sondhan-consumer-group

#Kafka-Topic-Version
kafka.topic.version=V2
#Kafka_Topics
kafka.topic.name=blood-donor-notification

#ElasticSearch Configuration
elasticsearch.host=localhost
elasticsearch.port=9200
elasticsearch.scheme=http

#Elastic-Index
elastic.bdf.donor.search.index=donor_search_index
elastic.bdf.donor.reg.index=registered_donors_index
elasticsearch.index.name.registered.users=registered_donors

#Geo
geo.fetch.lat.long.url=https://nominatim.openstreetmap.org/search?format=json&q=
default.geo.search.radius=30
geo.enrichment.poll-interval=30m

#Security
security.jwt.token.secret-key=@#$975312468;@#$5312468;@#$312468;@#$12468;@#$
security.jwt.access.token.validity=1200
security.jwt.refresh.token.validity=604800
rsa.private.key.cert.path=rsakeys/private_key.der
rsa.public.key.cert.path=rsakeys/public_key.der

#Redis
spring.data.redis.cluster.nodes=b-master-temp-redis:6380,a-slave-temp-redis:6379,c-slave-temp-redis:6381,c-master-temp-redis:6381,b-slave-temp-redis:6380,a-master-temp-redis:6379
#redis.cluster.hosts=redis://b-master-temp-redis:6380,redis://a-slave-temp-redis:6379,redis://c-slave-temp-redis:6381,redis://c-master-temp-redis:6381,redis://b-slave-temp-redis:6380,redis://a-master-temp-redis:6379

#App
app.redis.search.rate.limit.per.minute=30
app.search.max.raw.results=50