spring:
  session:
    store-type: redis
    redis:
      namespace: bdf-portal
      flush-mode: immediate


  datasource:
    url: jdbc:postgresql://localhost:5432/bd_db
    username: bduser
    password: bdpassword
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          format_sql: true
      show-sql: false

    sql:
      init:
        mode: never

  flyway:
    enabled: true
    locations: classpath:db/migration

sondhan:
  async:
    audit:
      core-pool-size: 2
      max-pool-size: 5
      queue-capacity: 100
      keep-alive-seconds: 60
    geo-fetch:
      core-pool-size: 5
      max-pool-size: 20
      queue-capacity: 500
      keep-alive-seconds: 60

  cors:
    allowed-origins:
      - ${CORS_ORIGIN_1:http://localhost:3000}
      - ${CORS_ORIGIN_2:http://localhost:3001}
      - ${CORS_ORIGIN_3:http://localhost:3002}

  pii:
    encryption-key: "@#$Ad01100110010110011001@#$"