package com.bd.blooddonorfinder.exception.enums;

public enum ErrorCode {
    INVALID_OTP,
    OTP_EXPIRED,
    OTP_SEND_FAILED,
    USER_NOT_FOUND,
    USER_ALREADY_EXISTS_WITH_PHONE,
    USER_ALREADY_EXISTS_WITH_EMAIL,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    RATE_LIMITED,
    ACCOUNT_LOCKED,
    USER_NOT_VERIFIED,
    UNAUTHORIZED,
    REFRESH_REUSE_ATTACK,
    INVALID_REQUEST,
    INVALID_EMAIL,
    ALREADY_VERIFIED,
    UNSUPPORTED_OTP_PURPOSE,
    OTP_ALREADY_USED
}
